### ISSUE TITLE
formatOnSave does not work when css is mapped to different type

### ISSUE THREAD

**Issue by chrishoage** [mrmlnc/vscode-stylefmt#101]
```
  "files.associations": {
    "*.css": "postcss"
  },
```

In a project I have postcss files named as css files, then map them with the `files.associations` config in my Workspace settings. 

When this is set `formatOnSave` has not effect. If I change the type to CSS `formatOnSave` works as expected. 

How do I get `formatOnSave` to work when PostCSS syntax is enabled?

**Comment by mrmlnc** [comment]
I don't know what I should do in this situation. It seems to me that it would cause a lot of problems. However, I will add this syntax.

**Comment by chrishoage** [comment]
> It seems to me that it would cause a lot of problems. 

Curious why you think it might cause problems? Stylefmt works with PostCSS no problem - provided it's been configured to do so.

**Comment by mrmlnc** [comment]
Available in 2.4.0.
