### ISSUE TITLE
Format for PostCSS language

### ISSUE THREAD

**Issue by svipas** [mrmlnc/vscode-stylefmt#102]
Hello,

can you add to the list `PostCSS` language? I'm using this plugin `https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language` which adds syntax coloring for `.css` files and it's language mode is `PostCSS` and formatting isn't working...

Formatting with `CTRL + SHIFT + P` and then select `stylefmt: Format CSS` works, but `CTRL + SHIFT + I` doesn't work for `PostCSS` language mode, only for `CSS`.

The problem is with `CTRL + SHIFT + I` to work with `PostCSS` language mode.

Thanks!

**Comment by mrmlnc** [comment]
Available in 2.4.0.

**Comment by svipas** [comment]
@mrmlnc Thank you! Tested and working! :+1:
