### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by taivu** [mrmlnc/vscode-stylefmt#115]
Can you update dependencies? I have some rules that arent being adhered to since vscode-stylefmt  uses a < 6 version.

**Comment by mrmlnc** [comment]
Thanks for issue! The new version of this package will be available very soon.

**Comment by mrmlnc** [comment]
Resolved by [2.5.0](https://github.com/mrmlnc/vscode-stylefmt/releases/tag/v2.5.0).

**Comment by taivu** [comment]
thank you for addressing the issue! cheers 🍻
