### ISSUE TITLE
Does it support sugarss?

### ISSUE THREAD

**Issue by muhajirdev** [mrmlnc/vscode-stylefmt#118]

**Comment by mrmlnc** [comment]
> **Understands CSS-like syntaxes:** stylefmt is powered by [PostCSS](https://github.com/postcss/postcss), so it understands any syntax that PostCSS can parse, including SCSS.

Most likely, Yes. Now I cannot work on this feature – PR welcome 🌮 

  - https://github.com/mrmlnc/vscode-stylefmt/blob/master/src/extension.ts#L31
  - https://github.com/postcss/sugarss

**Comment by mrmlnc** [comment]
Fixed by #159.
