### ISSUE TITLE
Use formatter API for better integration

### ISSUE THREAD

**Issue by jrieken** [mrmlnc/vscode-stylefmt#28]
I'd recommend to use the languages API to register a formatting edits provider because it will allow for a better integration in VS Code, esp wrt #21. There is the [`registerDocumentFormattingEditProvider`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4072)-function which is the way to introduce a formatter for certain document types. It will integrate you into the `Format Code` action (context menu, F1) and also into the `Format On Save`-feature.

It's just a matter of calling [this code](https://github.com/mrmlnc/vscode-stylefmt/blob/master/extension.js#L11) from within [DocumentFormattingEditProvider](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2071)

**Comment by mrmlnc** [comment]
Hello, @jrieken,

Thanks for your tip. I'll work on this today.

**Comment by mrmlnc** [comment]
@jrieken, Sorry for question, but I don't fully understand this functionality.

As I understand it, this API adds my plugin in `Format Code` command. But what if I add this functionality for all my own plugins? For example, `csscomb`, `autoprefixer` and `stylefmt` and then I press `Format Code`?

The question is, what is better to use `registerDocument(Range)FormattingEditProvider` or `onWillSaveTextDocument`?

**Comment by jrieken** [comment]
Definitely `registerDocument(Range)FormattingEditProvider` because then it's known as a formatter and we treat it like one (showing the entry in the context menu, calling you when `editor.formatOnSave` is set etc). 

When you register a provider you always say what [documents](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1499) you are registering it for, for instance _CSS files on disk_ is `{language: 'css', scheme: 'file'}` or _any html file_ is just `html`. When format is invoked we match the current document against the list of available providers and pick the _best match_. Since there is some ambiguity in that we are currently adding more toggles to disable our default/builtin providers - see https://github.com/Microsoft/vscode/issues/11609 for more details on that.

**Comment by mrmlnc** [comment]
Thanks you for your answer ❤️

But small clarification:
- I should provide `formatOnSave` option for users?
- In this case, I should have such functions in the plugin without `registerTextEditorCommand` for `stylefmt.execute` or just only `registerDocument(Range)FormattingEditProvider`?

**Comment by jrieken** [comment]
yeah - I would deprecate the custom `formatOnSave` option and rely on `registerDocument(Range)FormattingEditProvider`. Also note that `registerDocumentRangeFormattingEditProvider` is a _super-set-provider_ to `registerDocumentFormattingEditProvider` since the former is a special case of the latter.

**Comment by mrmlnc** [comment]
Thanks for the help, @jrieken.

I will update this plugin tomorrow.

**Comment by mrmlnc** [comment]
@jrieken, thanks for motivation. This API used in version `2.0.0`.

https://github.com/mrmlnc/vscode-stylefmt/releases/tag/2.0.0
