### ISSUE TITLE
Does it work with vscode-stylelint?

### ISSUE THREAD

**Issue by MartynasZilinskas** [mrmlnc/vscode-stylefmt#8]
Does this extension works with [stylelint](https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint)?

Because I have confing in `User settings`.

``` json
{
   "stylefmt.autoFormatOnSave":true,
   "stylelint.enable":true,
   "stylelint.configOverrides":{
      "indentation":4
   }
}
```

And it would be great if could work.

**Comment by mrmlnc** [comment]
Hello, @MartynasZilinskas,

I think it's a good idea, but now it can cause problems. Unfortunately, we use a slightly modified version of Stylefmt (hardcode in `/node_modules/stylefmt/lib/params.js`). I'll think about it and, if do not need to make many changes in the Stylefmt code, will release an update. 

I think it will be easy to do, but just in case, check this.

**Comment by mrmlnc** [comment]
Resolve in version 1.2.0 (see f8df5f2c7fffe022d942506fde765d4d08102b05).

# 

If you use this extension and satisfied with his work, then please leave a review in the marketplace.
