### ISSUE TITLE
Not working in vscode — CLI version does

### ISSUE THREAD

**Issue by ivancuric** [mrmlnc/vscode-stylefmt#80]
So, for a while now, stylefmt doesn't seem to be able to format CSS / SCSS documents.

I'm using vscode 1.10.1, stylefmt v2.2.2 and stylelint v0.23.0 which are the latest at the time of this writing.

I'm using a .stylelintrc file with the following options:
```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "number-leading-zero": "never",
    "declaration-empty-line-before": null,
    "at-rule-empty-line-before": null,
    "rule-empty-line-before": null,
    "rule-nested-empty-line-before": null,
    "selector-pseudo-element-colon-notation": null
  }
}
```
No errors are output (like when stylelint is out of date).

**Comment by mrmlnc** [comment]
Hello, @ivancuric,

Most likely this is related to #67. I'll look at your issue very soon.

**Comment by mrmlnc** [comment]
Please, look at `2.2.3` version. Potentially, this should fix the problem.
