### ISSUE TITLE
`CTRL + SHIFT + I` for formatting

### ISSUE THREAD

**Issue by svipas** [mrmlnc/vscode-stylefmt#94]
Hi,

My suggestion is to enable CSS formatting through `CTRL + SHIFT + I` as it is for e.g. with `prettier` which formats JS files. It's very handy when you use only 1 keybind to format your code instead of 2 keybinds. After this, this plugin will be the best CSS formatter ever :smiling_imp:

Thank you for your time!

**Comment by svipas** [comment]
@mrmlnc I don't know how, but it started to work with `CTRL + SHIFT + I` :smile:

**Comment by mrmlnc** [comment]
Sorry, but <kbd>CTRL + SHIFT + I</kbd> is `Format Document` or `Format Selection`? Technically `Format Document` is `Format Selection` but with `Range === Document (start + end)`.

**Comment by svipas** [comment]
@mrmlnc `Ctrl+Shift+I` - Format Document - editor.action.formatDocument. I don't know why, but before this issue it didn't worked and right now it works :smile:

**Comment by mrmlnc** [comment]
Maybe you have selection? Please, try again. It seems to me that it should work now.

**Comment by svipas** [comment]
@mrmlnc Maybe you understand me wrong. I don't know why, but for me formatting with `CTRL + SHIFT + I` was not working, it was working only with `CTRL + SHIFT + P` and I need to use `stylefmt: Format CSS`. But right now I tried again `CTRL + SHIFT + I`, because of my habit to format JS this way and BOOM it started to format CSS files. So this issue can be closed, because `CTRL + SHIFT + I` formatting is working correctly :+1:

**Comment by mrmlnc** [comment]
Thanks for clarification. If you have any questions you can create Issues 👍

**Comment by svipas** [comment]
@mrmlnc Thank you for such plugin!
